[categories]
BIRTH = "I need you to start off by telling me your name, place of birth, and date of birth?"
FAMILY = "Tell me a little bit about your family life before the war?"
SCHOOL = "Did you go to a public school, a private school?"
RELIGION = "And Judaism was important to you?"
RELATIONSHIPS = "Did you have friends who were Catholics?"
COMMUNITY = "Were there a lot of cultural or social organizations, political organizations in the town?"
VIOLENCE = "Did you see the shooting?"
JUDICIAL = "How many people were in the court?"
SURVIVOR = "You're sister is the only surviving?"
CITY_DESCRIPTION = "What was the name of the village where the Jewish Ghetto was?"
THANKS = "Thank you."
MEMORY = "Do you remember any of the in particular, Stephan?"
LABOR = "What kind of work did you do?"
AUDIO_ISSUE = "(Can't hear the tape)"
TIME = "How long would it normally take to walk?"
CLARIFICATION = "Let's stop here. Let's back up. What do you mean? Which guy arrived."
TRAVEL = "When and how did you come to the United States?"